--------------------------------------------------------
--  File created - Th? nãm-tháng m?t-16-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ADMIN
--------------------------------------------------------

  CREATE TABLE "TUNGDV"."ADMIN" 
   (	"ID" NUMBER(2,0), 
	"NAME" VARCHAR2(50 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"PASSWORD" VARCHAR2(100 BYTE), 
	"ADMIN" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EMPLOYEE_TBL
--------------------------------------------------------

  CREATE TABLE "TUNGDV"."EMPLOYEE_TBL" 
   (	"EMPLOYEE_ID" NUMBER(11,0), 
	"EMPLOYEE_FULLNAME" VARCHAR2(100 BYTE), 
	"EMPLOYEE_DESIGNATION" VARCHAR2(100 BYTE), 
	"EMPLOYEE_SALARY" NVARCHAR2(20)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SINHVIEN
--------------------------------------------------------

  CREATE TABLE "TUNGDV"."SINHVIEN" 
   (	"ID" NUMBER(2,0), 
	"NAME" VARCHAR2(50 BYTE), 
	"CLASSNAME" VARCHAR2(50 BYTE), 
	"AGE" NUMBER(3,0), 
	"MSV" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table STUDENT
--------------------------------------------------------

  CREATE TABLE "TUNGDV"."STUDENT" 
   (	"ID" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(20 BYTE), 
	"CLASSNAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into TUNGDV.ADMIN
SET DEFINE OFF;
Insert into TUNGDV.ADMIN (ID,NAME,EMAIL,PASSWORD,ADMIN) values ('8','Admin','admin1102@gmail.com','123456','0');
Insert into TUNGDV.ADMIN (ID,NAME,EMAIL,PASSWORD,ADMIN) values ('9','Admin','admin1103@gmail.com','d8QjCtjhcnDzVyPG6tRjCg==','0');
REM INSERTING into TUNGDV.EMPLOYEE_TBL
SET DEFINE OFF;
Insert into TUNGDV.EMPLOYEE_TBL (EMPLOYEE_ID,EMPLOYEE_FULLNAME,EMPLOYEE_DESIGNATION,EMPLOYEE_SALARY) values ('1','Daniel','Technical Lead','1300000.00');
Insert into TUNGDV.EMPLOYEE_TBL (EMPLOYEE_ID,EMPLOYEE_FULLNAME,EMPLOYEE_DESIGNATION,EMPLOYEE_SALARY) values ('2','Charlotte','Technical Lead','1100000.00');
Insert into TUNGDV.EMPLOYEE_TBL (EMPLOYEE_ID,EMPLOYEE_FULLNAME,EMPLOYEE_DESIGNATION,EMPLOYEE_SALARY) values ('3','Rakesh','Software Developer','550000.00');
Insert into TUNGDV.EMPLOYEE_TBL (EMPLOYEE_ID,EMPLOYEE_FULLNAME,EMPLOYEE_DESIGNATION,EMPLOYEE_SALARY) values ('4','Jane','Senior Software Developer','970000.00');
Insert into TUNGDV.EMPLOYEE_TBL (EMPLOYEE_ID,EMPLOYEE_FULLNAME,EMPLOYEE_DESIGNATION,EMPLOYEE_SALARY) values ('5','Smith','UI Developer','1000000.00');
Insert into TUNGDV.EMPLOYEE_TBL (EMPLOYEE_ID,EMPLOYEE_FULLNAME,EMPLOYEE_DESIGNATION,EMPLOYEE_SALARY) values ('6','Bob','Associate HR','80000.00');
Insert into TUNGDV.EMPLOYEE_TBL (EMPLOYEE_ID,EMPLOYEE_FULLNAME,EMPLOYEE_DESIGNATION,EMPLOYEE_SALARY) values ('7','Rahul','Senior Software Developer','90000.00');
Insert into TUNGDV.EMPLOYEE_TBL (EMPLOYEE_ID,EMPLOYEE_FULLNAME,EMPLOYEE_DESIGNATION,EMPLOYEE_SALARY) values ('8','Rakesh','UI Developer','25000.00');
Insert into TUNGDV.EMPLOYEE_TBL (EMPLOYEE_ID,EMPLOYEE_FULLNAME,EMPLOYEE_DESIGNATION,EMPLOYEE_SALARY) values ('9','Udit','Junior Developer','35000.00');
Insert into TUNGDV.EMPLOYEE_TBL (EMPLOYEE_ID,EMPLOYEE_FULLNAME,EMPLOYEE_DESIGNATION,EMPLOYEE_SALARY) values ('10','Jai','Technical Lead','45000.00');
Insert into TUNGDV.EMPLOYEE_TBL (EMPLOYEE_ID,EMPLOYEE_FULLNAME,EMPLOYEE_DESIGNATION,EMPLOYEE_SALARY) values ('11','Nikhil','UI Developer','55000.00');
Insert into TUNGDV.EMPLOYEE_TBL (EMPLOYEE_ID,EMPLOYEE_FULLNAME,EMPLOYEE_DESIGNATION,EMPLOYEE_SALARY) values ('12','Somesh','Senior Software Developer','65000.00');
Insert into TUNGDV.EMPLOYEE_TBL (EMPLOYEE_ID,EMPLOYEE_FULLNAME,EMPLOYEE_DESIGNATION,EMPLOYEE_SALARY) values ('13','Rajesh','Manager','75000.00');
Insert into TUNGDV.EMPLOYEE_TBL (EMPLOYEE_ID,EMPLOYEE_FULLNAME,EMPLOYEE_DESIGNATION,EMPLOYEE_SALARY) values ('14','Ankit','UI Developer','85000.00');
Insert into TUNGDV.EMPLOYEE_TBL (EMPLOYEE_ID,EMPLOYEE_FULLNAME,EMPLOYEE_DESIGNATION,EMPLOYEE_SALARY) values ('15','Ratan','Technical Lead','95000.00');
REM INSERTING into TUNGDV.SINHVIEN
SET DEFINE OFF;
Insert into TUNGDV.SINHVIEN (ID,NAME,CLASSNAME,AGE,MSV) values ('20','huy','CNTT1','20','013');
Insert into TUNGDV.SINHVIEN (ID,NAME,CLASSNAME,AGE,MSV) values ('12','Nam','CNTT1','22','005');
Insert into TUNGDV.SINHVIEN (ID,NAME,CLASSNAME,AGE,MSV) values ('10','Ti?n','CNTT1','14','001');
Insert into TUNGDV.SINHVIEN (ID,NAME,CLASSNAME,AGE,MSV) values ('11','Hùng','CNTT3','21','004');
Insert into TUNGDV.SINHVIEN (ID,NAME,CLASSNAME,AGE,MSV) values ('14','Sõn','CNTT2','22','007');
Insert into TUNGDV.SINHVIEN (ID,NAME,CLASSNAME,AGE,MSV) values ('15','Ti?n','CNTT2','22','008');
Insert into TUNGDV.SINHVIEN (ID,NAME,CLASSNAME,AGE,MSV) values ('17','Hùng','CNTT1','22','010');
Insert into TUNGDV.SINHVIEN (ID,NAME,CLASSNAME,AGE,MSV) values ('18','Ti?n','CNTT2','22','011');
Insert into TUNGDV.SINHVIEN (ID,NAME,CLASSNAME,AGE,MSV) values ('16','Ti?n','CNTT2','22','009');
Insert into TUNGDV.SINHVIEN (ID,NAME,CLASSNAME,AGE,MSV) values ('19','Hùng','CNTT2','44','012');
Insert into TUNGDV.SINHVIEN (ID,NAME,CLASSNAME,AGE,MSV) values ('21','Sõn','CNTT1','22','014');
REM INSERTING into TUNGDV.STUDENT
SET DEFINE OFF;
Insert into TUNGDV.STUDENT (ID,NAME,CLASSNAME) values ('1','TUNG','CNTT3');
Insert into TUNGDV.STUDENT (ID,NAME,CLASSNAME) values ('2','TRANG','CNTT2');
Insert into TUNGDV.STUDENT (ID,NAME,CLASSNAME) values ('3','HIEU','CNTT1');
--------------------------------------------------------
--  DDL for Index SINHVIEN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TUNGDV"."SINHVIEN_PK" ON "TUNGDV"."SINHVIEN" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0011127
--------------------------------------------------------

  CREATE UNIQUE INDEX "TUNGDV"."SYS_C0011127" ON "TUNGDV"."EMPLOYEE_TBL" ("EMPLOYEE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ADMIN
--------------------------------------------------------

  ALTER TABLE "TUNGDV"."ADMIN" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLOYEE_TBL
--------------------------------------------------------

  ALTER TABLE "TUNGDV"."EMPLOYEE_TBL" MODIFY ("EMPLOYEE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "TUNGDV"."EMPLOYEE_TBL" MODIFY ("EMPLOYEE_FULLNAME" NOT NULL ENABLE);
 
  ALTER TABLE "TUNGDV"."EMPLOYEE_TBL" MODIFY ("EMPLOYEE_DESIGNATION" NOT NULL ENABLE);
 
  ALTER TABLE "TUNGDV"."EMPLOYEE_TBL" MODIFY ("EMPLOYEE_SALARY" NOT NULL ENABLE);
 
  ALTER TABLE "TUNGDV"."EMPLOYEE_TBL" ADD PRIMARY KEY ("EMPLOYEE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SINHVIEN
--------------------------------------------------------

  ALTER TABLE "TUNGDV"."SINHVIEN" ADD CONSTRAINT "SINHVIEN_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "TUNGDV"."SINHVIEN" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "TUNGDV"."SINHVIEN" MODIFY ("NAME" NOT NULL ENABLE);
